accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/',LogoutView.as_view(),name ='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
]

book_bug_main/book_bug_main/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

bookbug/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls'),),
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null = False)

homeapp/models.py
from django.db import models

# Create your models here.

accountapp/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello')
    template_name = 'accountapp/create.html'


def hello_world():
    return None

book_bug_main/acountapp/views.py
from django.shortcuts import render

# Create your views here.

homeapp/views.py
from django.shortcuts import render

# Create your views here.

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}

{% block content %}
  <div style="text-align: centers">
    <form action="{% url 'accountapp:create' %}" method="post">
      {% csrf_token %}
      {{ form }}

      <input type="submit">
    </form>
  </div>
{% endblock %}

accountapp/templates/accountapp/helloworld.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <div>
      <h4>Login</h4>
    </div>
    <div>
      <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" >
      </form>
    </div>
  </div>
{% endblock %}

book_bug_main/acountapp/templates/accountapp/mypage.html
{% extends 'base.html' %}

<!-- Product section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..." /></div>
                    <div class="col-md-6">

                        <h1 class="display-5 fw-bolder">User님의 서재</h1>
                        <p class="lead">안녕하세요 User님의 서재입니다.</p>
                        <div class="d-flex">
                            <button class="btn btn-outline-dark flex-shrink-0" type="button">
                                <i class="follow"></i>
                                Follow
                            </button>
                            <button class="btn btn-outline-dark flex-shrink-0" type="button">
                                    <i class="follow"></i>
                                        프로필 편집
                            </button>
                        </div>
                        <div>
                                <p></p>
                                <p class="lead">책벌레 등급</p>
                                <p class="lead">지금 나의 인생책은?</p>

                        </div>
                    </div>
                </div>
            </div>
        </section>

book_bug_main/templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR';">

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

book_bug_main/templates/footer.html
 <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">프로젝트 책벌레</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>

book_bug_main/templates/head.html
<!DOCTYPE html>
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>

    <!--  BOOTSTRAP LINK  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!--  GOOGLE FONTS LINK  -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <!-- GOOGLE MATERIAL ICONs -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <!--  DEFAULT CSS LINK  -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.ttf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
    </style>

</head>

book_bug_main/templates/header.html
<!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">책벌레</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!"></a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">My Page</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">전체 도서</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">독서노트</a></li>
                                <li><a class="dropdown-item" href="#!">책장</a></li>
                                <li><a class="dropdown-item" href="#!">통계</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="logout"></i>
                            로그아웃
                        </button>
                    </form>
                </div>
            </div>
        </nav>

homeapp/templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include 'head.html' %}
<body>

    {% include 'navbar.html' %}
    {% include 'header.html' %}
    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}
</body>
</html>

homeapp/templates/footer.html
 <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; 책벌레 테스트 메인페이지</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>

homeapp/templates/head.html
 {% load static %}
<head>
    <title>BookBug</title>


      <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>book-bug_test</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

        <!-- DEFAULT CSS LINK -->
        <link rel = "stylesheet" type="text/css" href="{% static 'base.css' %}">
</head>

homeapp/templates/header.html
 <!-- Header-->
        <header style="background: rgba(162, 225, 42, 0.65);" class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">당신을 위한 BOOK</h1>
                    <p class="lead fw-normal text-black-50 mb-0">도서 전문 커넥팅 서비스</p>
                </div>
            </div>
        </header>

homeapp/templates/navbar.html
 <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!" style="color: rgb(69, 101, 0);">책벌레</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-book-fill me-1"></i>
                            찜한 도서 개수
                            <span class="badge bg-dark text-white ms-1 rounded-pill">개수 표시 여기에</span>
                        </button>
                    </form>
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">도서</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">000 총류</a></li>
                                <li><a class="dropdown-item" href="#!">100 철학</a></li>
                                <li><a class="dropdown-item" href="#!">200 종교</a></li>
                                <li><a class="dropdown-item" href="#!">300 사회학</a></li>
                                <li><a class="dropdown-item" href="#!">400 자연과학</a></li>
                                <li><a class="dropdown-item" href="#!">500 기술과학</a></li>
                                <li><a class="dropdown-item" href="#!">600 예술</a></li>
                                <li><a class="dropdown-item" href="#!">700 언어</a></li>
                                <li><a class="dropdown-item" href="#!">800 문학</a></li>
                                <li><a class="dropdown-item" href="#!">900 역사</a></li>
                            </ul>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">개인 닉네임 여기에</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">내 책방</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">보관함</a></li>
                                <li><a class="dropdown-item" href="#!">정보 수정</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>